[info]
title = "Sistema de Consultas Multimodal RAG y LoRA Fine-Tuned para Manuales de Mantenimiento en Plantas Concentradoras de Cobre"
degree = "MAESTRO EN CIENCIAS CON MENCIÓN EN INTELIGENCIA ARTIFICIAL"
student = "Johan Manuel Callomamani Buendia"
advisor = "DR. GLEN DARIO RODRIGUEZ RAFAEL"
location = "LIMA, PERU"
year = "2025"

[institution]
name = "UNIVERSIDAD NACIONAL DE INGENIERÍA"
faculty = "UNIDAD DE POSTGRADO FACULTAD DE INGENIERIA INDUSTRIAL Y DE SISTEMAS"

[project]
area = "UNIDAD DE POSGRADO FIIS"
place = "Unidad Minera Mina Justa - San Juan de Marcona-Nazca"
duration = "15 MESES (Setiembre 2025 - Noviembre 2026)"
has_logo = true   # <--- AGREGA ESTA LÍNEA